steps:
  # Step 1: Build the container image using the Dockerfile and tag it for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tarot-divination-dev:$COMMIT_SHA', '.']

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tarot-divination-dev:$COMMIT_SHA']

  # Step 3: Deploy container image to Cloud Run using a highly optimized, lightweight alpine-based gcloud tool
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tarot-divination-dev'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tarot-divination-dev:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tarot-divination-dev:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
